{"name": "test_enter_wrong_login_response_error", "status": "passed", "start": 1730872797072, "stop": 1730872798030, "uuid": "6d98477e-6cb1-4bee-9e0e-4ad5ff518f5a", "historyId": "adf88e9b9ecbb2bf53a24f55079925c8", "testCaseId": "adf88e9b9ecbb2bf53a24f55079925c8", "fullName": "tests.test_authorize_courier.TestAuthorizeCourier#test_enter_wrong_login_response_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorize_courier"}, {"name": "subSuite", "value": "TestAuthorizeCourier"}, {"name": "host", "value": "DESKTOP-GKI6E5O"}, {"name": "thread", "value": "2708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorize_courier"}]}